apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs:
    path: /volumes/v2
    server: 192.168.137.103
