apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy-nfs
  namespace: xielonglong
  labels:
    app: mydeploy
    rel: release
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      rel: canary
  template:
    metadata:
      namespace: xielonglong
      labels:
        app: myapp
        rel: canary
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
        volumeMounts:
        - name: myvol
          mountPath: /usr/share/nginx/html
      volumes:
      - name: myvol
        nfs:
          path: /volumes/v1
          server: 192.168.137.103
      restartPolicy: Always
