apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: mysc
provisioner: kubernetes.io/rbd
parameters:
  monitors: 192.168.137.120:6789,192.168.137.121:6789,192.168.137.122:6789
  adminId: admin
  adminSecretName: ceph-admin
  adminSecretNamespace: default
  pool: kube
  userId: kube
  userSecretName: ceph-kube 
