apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeploy
  namespace: xielonglong
spec:
  replicas: 3
  selector:
    matchLabels:
      app: myapp
      rel: canary
  template:
    metadata:
      name: mypod
      labels:
        app: myapp
        rel: canary
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        ports:
        - name: http
          containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mysvc
  namespace: xielonglong
spec:
  selector:
    app: myapp
    rel: canary
  ports:
  - name: http
    port: 80
    targetPort: 80
    nodePort: 30080
  type: NodePort

