apiVersion: v1
kind: Pod
metadata:
  name: pod-demo
  namespace: default
spec:
  containers:
  - name: myapp
    image: nginx:latest
 # hostNetwork: true
    ports:
    - name: http
      containerPort: 80
      hostPort: 8080

