apiVersion: v1
kind: Pod
metadata:
  name: readness-pod
  namespace: default
spec:
  containers:
  - name: nginx
    image: nginx:latest
    imagePullPolicy: IfNotPresent
    command:
    - /bin/bash
    - -c
    - "touch /usr/share/nginx/html/xielonglong.html;sleep 30;rm /usr/share/nginx/html/xielonglong.html;sleep 3600"
    readinessProbe:
      exec:
        command:
        - /bin/bash
        - -c
        - "test -e /usr/share/nginx/html/xielonglong.html"
      failureThreshold: 2
      periodSeconds: 5
      successThreshold: 2
      timeoutSeconds: 2
      initialDelaySeconds: 5
