apiVersion: v1
kind: LimitRange
metadata:
  name: mylimit
  namespace: xielonglong
spec:
  limits:
  - type: Pod
    max:
      cpu: 1
    min:
      cpu: "200m"
    maxLimitRequestRatio:
      cpu: 4
  - type: Container
    default:
      cpu: "300m"
    defaultRequest:
      cpu: "100m"
    max:
      cpu: "400m"
    min:
      cpu: "50m"
    maxLimitRequestRatio:
      cpu: 3
