apiVersion: v1
kind: Pod
metadata: 
  name: mypod
  namespace: xielonglong
spec:
  containers:
  - name: nginx
    image: nginx
    resources:
      requests:
        cpu: 200m
      limits:
        cpu: 200m
  - name: myapp
    image: nginx
    resources:
      requests:
        cpu: 200m
      limits:
        cpu: 200m
  - name: mynginx
    image: nginx
    resources:
      requests:
        cpu: 200m
      limits:
        cpu: 200m
