kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  namespace: default
  name: myrole
rules:
- apiGroups: [""]   # "" 表示core API group
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
