apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv4
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    server: 192.168.137.103
    path: /volumes/v4
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv5
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    server: 192.168.137.103
    path: /volumes/v5
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv6
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    server: 192.168.137.103
    path: /volumes/v6
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv7
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    server: 192.168.137.103
    path: /volumes/v7
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv8
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    server: 192.168.137.103
    path: /volumes/v8
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mypv9
spec:
  accessModes:
  - ReadWriteOnce
  - ReadWriteMany
  capacity:
    storage: 5Gi
  nfs:
    server: 192.168.137.103
    path: /volumes/v9
---
